services:

  mongo:
    image: mongo:8.2.4
    container_name: ${COMPOSE_LEAD}-${COMPOSE_NAME}
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: ${COMPOSE_CPUS}
          memory: ${COMPOSE_MEMO} # On Docker Swarm, move resource limits into 'deploy.resources.limits'
    volumes:
      - ${COMPOSE_DATA}:/data/db
    restart: unless-stopped

volumes:
  mongodb-data:
    driver: local