services:

  mongo:
    ports:
      - ${COMPOSE_HOST}:${COMPOSE_PORT}:27017
    networks:
      net: {}

networks:
  net:
    driver: bridge
    external: true
    name: ${COMPOSE_LEAD}-${COMPOSE_CNET}
  default:
    external: true
    name: ${COMPOSE_LEAD}-${COMPOSE_CNET}