# docker-compose.public.yml - standalone, world accessible
services:

  mongo:
    ports:
      - ${COMPOSE_PORT}:27017
    networks:
      - net

networks:
  net:
    driver: bridge
    name: ${COMPOSE_LEAD}-${COMPOSE_CNET}